// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/week4/week4.proto

package week4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWeek4Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateWeek4Request) Reset() {
	*x = CreateWeek4Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWeek4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeek4Request) ProtoMessage() {}

func (x *CreateWeek4Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeek4Request.ProtoReflect.Descriptor instead.
func (*CreateWeek4Request) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{0}
}

type CreateWeek4Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateWeek4Reply) Reset() {
	*x = CreateWeek4Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWeek4Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeek4Reply) ProtoMessage() {}

func (x *CreateWeek4Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeek4Reply.ProtoReflect.Descriptor instead.
func (*CreateWeek4Reply) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{1}
}

type UpdateWeek4Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateWeek4Request) Reset() {
	*x = UpdateWeek4Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWeek4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWeek4Request) ProtoMessage() {}

func (x *UpdateWeek4Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWeek4Request.ProtoReflect.Descriptor instead.
func (*UpdateWeek4Request) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{2}
}

type UpdateWeek4Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateWeek4Reply) Reset() {
	*x = UpdateWeek4Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWeek4Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWeek4Reply) ProtoMessage() {}

func (x *UpdateWeek4Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWeek4Reply.ProtoReflect.Descriptor instead.
func (*UpdateWeek4Reply) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{3}
}

type DeleteWeek4Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWeek4Request) Reset() {
	*x = DeleteWeek4Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWeek4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWeek4Request) ProtoMessage() {}

func (x *DeleteWeek4Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWeek4Request.ProtoReflect.Descriptor instead.
func (*DeleteWeek4Request) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{4}
}

type DeleteWeek4Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWeek4Reply) Reset() {
	*x = DeleteWeek4Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWeek4Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWeek4Reply) ProtoMessage() {}

func (x *DeleteWeek4Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWeek4Reply.ProtoReflect.Descriptor instead.
func (*DeleteWeek4Reply) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{5}
}

type GetWeek4Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWeek4Request) Reset() {
	*x = GetWeek4Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeek4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeek4Request) ProtoMessage() {}

func (x *GetWeek4Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeek4Request.ProtoReflect.Descriptor instead.
func (*GetWeek4Request) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{6}
}

type GetWeek4Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWeek4Reply) Reset() {
	*x = GetWeek4Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeek4Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeek4Reply) ProtoMessage() {}

func (x *GetWeek4Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeek4Reply.ProtoReflect.Descriptor instead.
func (*GetWeek4Reply) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{7}
}

type ListWeek4Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWeek4Request) Reset() {
	*x = ListWeek4Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeek4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeek4Request) ProtoMessage() {}

func (x *ListWeek4Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeek4Request.ProtoReflect.Descriptor instead.
func (*ListWeek4Request) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{8}
}

type ListWeek4Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWeek4Reply) Reset() {
	*x = ListWeek4Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_week4_week4_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWeek4Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeek4Reply) ProtoMessage() {}

func (x *ListWeek4Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_week4_week4_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeek4Reply.ProtoReflect.Descriptor instead.
func (*ListWeek4Reply) Descriptor() ([]byte, []int) {
	return file_api_week4_week4_proto_rawDescGZIP(), []int{9}
}

var File_api_week4_week4_proto protoreflect.FileDescriptor

var file_api_week4_week4_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x2f, 0x77, 0x65, 0x65, 0x6b,
	0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65,
	0x6b, 0x34, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b,
	0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b,
	0x34, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x65, 0x6b,
	0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74,
	0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xef, 0x02, 0x0a, 0x05, 0x57,
	0x65, 0x65, 0x6b, 0x34, 0x12, 0x49, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65,
	0x65, 0x6b, 0x34, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x49, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x12, 0x1d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x77, 0x65, 0x65, 0x6b, 0x34, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b,
	0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77,
	0x65, 0x65, 0x6b, 0x34, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x65, 0x6b, 0x34,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x40, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x57, 0x65, 0x65, 0x6b,
	0x34, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x65,
	0x6b, 0x34, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x65, 0x65, 0x6b, 0x34, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65, 0x6b, 0x34,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x57, 0x65, 0x65, 0x6b, 0x34, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x24, 0x0a, 0x09,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x50, 0x01, 0x5a, 0x15, 0x77, 0x65, 0x65,
	0x6b, 0x34, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x65, 0x6b, 0x34, 0x3b, 0x77, 0x65, 0x65,
	0x6b, 0x34, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_week4_week4_proto_rawDescOnce sync.Once
	file_api_week4_week4_proto_rawDescData = file_api_week4_week4_proto_rawDesc
)

func file_api_week4_week4_proto_rawDescGZIP() []byte {
	file_api_week4_week4_proto_rawDescOnce.Do(func() {
		file_api_week4_week4_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_week4_week4_proto_rawDescData)
	})
	return file_api_week4_week4_proto_rawDescData
}

var file_api_week4_week4_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_week4_week4_proto_goTypes = []interface{}{
	(*CreateWeek4Request)(nil), // 0: api.week4.CreateWeek4Request
	(*CreateWeek4Reply)(nil),   // 1: api.week4.CreateWeek4Reply
	(*UpdateWeek4Request)(nil), // 2: api.week4.UpdateWeek4Request
	(*UpdateWeek4Reply)(nil),   // 3: api.week4.UpdateWeek4Reply
	(*DeleteWeek4Request)(nil), // 4: api.week4.DeleteWeek4Request
	(*DeleteWeek4Reply)(nil),   // 5: api.week4.DeleteWeek4Reply
	(*GetWeek4Request)(nil),    // 6: api.week4.GetWeek4Request
	(*GetWeek4Reply)(nil),      // 7: api.week4.GetWeek4Reply
	(*ListWeek4Request)(nil),   // 8: api.week4.ListWeek4Request
	(*ListWeek4Reply)(nil),     // 9: api.week4.ListWeek4Reply
}
var file_api_week4_week4_proto_depIdxs = []int32{
	0, // 0: api.week4.Week4.CreateWeek4:input_type -> api.week4.CreateWeek4Request
	2, // 1: api.week4.Week4.UpdateWeek4:input_type -> api.week4.UpdateWeek4Request
	4, // 2: api.week4.Week4.DeleteWeek4:input_type -> api.week4.DeleteWeek4Request
	6, // 3: api.week4.Week4.GetWeek4:input_type -> api.week4.GetWeek4Request
	8, // 4: api.week4.Week4.ListWeek4:input_type -> api.week4.ListWeek4Request
	1, // 5: api.week4.Week4.CreateWeek4:output_type -> api.week4.CreateWeek4Reply
	3, // 6: api.week4.Week4.UpdateWeek4:output_type -> api.week4.UpdateWeek4Reply
	5, // 7: api.week4.Week4.DeleteWeek4:output_type -> api.week4.DeleteWeek4Reply
	7, // 8: api.week4.Week4.GetWeek4:output_type -> api.week4.GetWeek4Reply
	9, // 9: api.week4.Week4.ListWeek4:output_type -> api.week4.ListWeek4Reply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_week4_week4_proto_init() }
func file_api_week4_week4_proto_init() {
	if File_api_week4_week4_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_week4_week4_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWeek4Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_week4_week4_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWeek4Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_week4_week4_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWeek4Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_week4_week4_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWeek4Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_week4_week4_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWeek4Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_week4_week4_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWeek4Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_week4_week4_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeek4Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_week4_week4_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeek4Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_week4_week4_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeek4Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_week4_week4_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWeek4Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_week4_week4_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_week4_week4_proto_goTypes,
		DependencyIndexes: file_api_week4_week4_proto_depIdxs,
		MessageInfos:      file_api_week4_week4_proto_msgTypes,
	}.Build()
	File_api_week4_week4_proto = out.File
	file_api_week4_week4_proto_rawDesc = nil
	file_api_week4_week4_proto_goTypes = nil
	file_api_week4_week4_proto_depIdxs = nil
}
